version: '3.5'
    
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_shopper
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: .
    command: npm run start:prod
    ports: 
      - "3000:3000"
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /openapi.json
      BASE_URL: /swagger
    ports:
      - "3001:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
  
volumes:
    postgres:
    swagger: